services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: permit-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: permit_management_prod
      POSTGRES_USER: permit_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U permit_user -d permit_management_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Permit Management Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: permit-server
    restart: unless-stopped
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/permit_management_prod
      DB_USER: permit_user
      DB_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
      JWT_SECRET: ${JWT_SECRET:-change-this-jwt-secret-key-in-production}
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      ENVIRONMENT: production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
